### ISSUE TITLE
Links produce an HTTPS error on the live demos

### ISSUE THREAD

**Issue by wilomgfx** [naltatis/micro-frontends-in-action-code#9]
I'm getting `ERR_SSL_PROTOCOL_ERROR` on chrome `Version 83.0.4103.116 (Official Build) (64-bit)`

![image](https://user-images.githubusercontent.com/6611491/86854231-06c5d300-c086-11ea-9fa9-e9362624da18.png)

and on latest firefox 

```
An error occurred during a connection to 01_pages_links.the-tractor.store:3001. 
SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

It also does not work on latest safari

**Comment by naltatis** [comment]
Thanks @wilomgfx,

Seems like I've gone a little too far with the security headers. Two weeks ago I added the `strict-transport-security: max-age=15768000; includeSubDomains; preload` header to the overview page which is delivered via HTTPS.
The individual examples are delivered via HTTP, but since I've accidentally added `includeSubDomains`, the browsers will try to access the examples also via HTTPS.

I've removed the `includeSubDomains` for now. Seems like all browsers (I've tested Chrome, Safari, Firefox) updated their HSTS knowledge right away after opening the overview page again.

But this is a good reminder to look into the topic of enabling SSL for all examples.

Can you check if the change also works for you?
\ naltatis

**Comment by wilomgfx** [comment]
Works fine now :) thanks a lot!

Great book BTW, we are about to dive deep into micro frontends at work :)
